version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbo_app
    ports:
      - "5432:5432"
    networks:
      - my_network

  dbo-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: dbo_app
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      SECRET: rahasia

networks:
  my_network: